spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  instance:
    metadataMap:
      zone: zone1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:  
  port: ${PORT:8081}

management:
  security:
    enabled: false
    
sample:
  string:
    property: Client Application Yes
  int:
    property: 4
